server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.206.164:3307/db_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.206.164:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml

#logging:
#  level:
#    com.atguigu.guli.service.edu:debug
#  config: classpath:logback-spring.xml

logging:
  level:
    com.atguigu.guli.service.edu: debug
  config: classpath:logback-spring-dev.xml
ribbon:
  ConnectTimeout: 100000 #连接建立的超时时长，默认1秒
  ReadTimeout: 100000 #处理请求的超时时间，默认为1秒
feign:
  sentinel:
    enabled: true
